-- Name: Tatiana Sutulova
-- Student id: 30806151

-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-09-16 20:50:19 SGT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

SET ECHO ON
SPOOL mm_schema_output.txt

DROP TABLE centre CASCADE CONSTRAINTS;

DROP TABLE class_staff CASCADE CONSTRAINTS;

DROP TABLE class_type CASCADE CONSTRAINTS;

DROP TABLE facility CASCADE CONSTRAINTS;

DROP TABLE fitness_assessment CASCADE CONSTRAINTS;

DROP TABLE fitness_class CASCADE CONSTRAINTS;

DROP TABLE member CASCADE CONSTRAINTS;

DROP TABLE member_session_attendance CASCADE CONSTRAINTS;

DROP TABLE sign_up CASCADE CONSTRAINTS;

DROP TABLE staff CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE centre (
    centre_id             NUMBER(3) NOT NULL,
    centre_name           VARCHAR2(50 CHAR) NOT NULL,
    centre_addr_street    VARCHAR2(50 CHAR) NOT NULL,
    centre_addr_town      VARCHAR2(50 CHAR) NOT NULL,
    centre_addr_postcode  CHAR(5 CHAR) NOT NULL,
    centre_phone          CHAR(10 CHAR) NOT NULL,
    manager_id            NUMBER(8) NOT NULL
);

COMMENT ON COLUMN centre.centre_id IS
    'Centre unique identifier';

COMMENT ON COLUMN centre.centre_name IS
    'Name of the centre';

COMMENT ON COLUMN centre.centre_addr_street IS
    'Part of the centre address: street';

COMMENT ON COLUMN centre.centre_addr_town IS
    'Part of the centre address: town';

COMMENT ON COLUMN centre.centre_addr_postcode IS
    'Part of the centre address: postcode';

COMMENT ON COLUMN centre.centre_phone IS
    'Centre phone number';

COMMENT ON COLUMN centre.manager_id IS
    'Unique identifier for the staff';

CREATE UNIQUE INDEX centre__idx ON
    centre (
        manager_id
    ASC );

ALTER TABLE centre ADD CONSTRAINT fitness_centre_pk PRIMARY KEY ( centre_id );

CREATE TABLE class_staff (
    staff_id            NUMBER(8) NOT NULL,
    class_no            NUMBER(4) NOT NULL,
    centre_id           NUMBER(3) NOT NULL,
    class_staff_leader  CHAR(1 CHAR) NOT NULL
);

ALTER TABLE class_staff
    ADD CONSTRAINT chk_leader CHECK ( class_staff_leader IN ( 'N', 'Y' ) );

COMMENT ON COLUMN class_staff.staff_id IS
    'Unique identifier for the staff';

COMMENT ON COLUMN class_staff.class_no IS
    'Unique within the centre class identifier ';

COMMENT ON COLUMN class_staff.centre_id IS
    'Centre unique identifier';

COMMENT ON COLUMN class_staff.class_staff_leader IS
    'Defines whether the staff member is a class leader:
	- Y: yes
	- N: no';

ALTER TABLE class_staff
    ADD CONSTRAINT class_staff_pk PRIMARY KEY ( staff_id,
                                                class_no,
                                                centre_id );

CREATE TABLE class_type (
    class_type_name  VARCHAR2(20 CHAR) NOT NULL,
    class_type_id    NUMBER(7) NOT NULL
);

COMMENT ON COLUMN class_type.class_type_name IS
    'The name of the class type';

COMMENT ON COLUMN class_type.class_type_id IS
    'Unique identifier of a class type';

ALTER TABLE class_type ADD CONSTRAINT class_type_pk PRIMARY KEY ( class_type_id );

CREATE TABLE facility (
    fac_room_no   NUMBER(3) NOT NULL,
    centre_id     NUMBER(3) NOT NULL,
    fac_name      VARCHAR2(50 CHAR) NOT NULL,
    fac_descr     VARCHAR2(50 CHAR),
    fac_capacity  NUMBER(3) NOT NULL
);

COMMENT ON COLUMN facility.fac_room_no IS
    'The unique within a centre facility id';

COMMENT ON COLUMN facility.centre_id IS
    'Centre unique identifier';

COMMENT ON COLUMN facility.fac_name IS
    'Facility name';

COMMENT ON COLUMN facility.fac_descr IS
    'Facility description';

COMMENT ON COLUMN facility.fac_capacity IS
    'Capacity of the facility';

ALTER TABLE facility ADD CONSTRAINT facility_pk PRIMARY KEY ( fac_room_no,
                                                              centre_id );

CREATE TABLE fitness_assessment (
    fitassess_date            DATE NOT NULL,
    member_no                 NUMBER(8) NOT NULL,
    staff_id                  NUMBER(8) NOT NULL,
    fitassess_weight          NUMBER(3) NOT NULL,
    fitassess_blood_pressure  VARCHAR2(7 CHAR) NOT NULL,
    fitassess_bmi             NUMBER(3, 1) NOT NULL,
    fitassess_vo2max          NUMBER(3, 1) NOT NULL
);

COMMENT ON COLUMN fitness_assessment.fitassess_date IS
    'Date of the fitness assessment';

COMMENT ON COLUMN fitness_assessment.member_no IS
    'Unique identifier of the member';

COMMENT ON COLUMN fitness_assessment.staff_id IS
    'Unique identifier for the staff';

COMMENT ON COLUMN fitness_assessment.fitassess_weight IS
    'Fitness assessment weight measured';

COMMENT ON COLUMN fitness_assessment.fitassess_blood_pressure IS
    'Fitness assessment blood pressure measured';

COMMENT ON COLUMN fitness_assessment.fitassess_bmi IS
    'Fitness assessment BMI measured';

COMMENT ON COLUMN fitness_assessment.fitassess_vo2max IS
    'Fitness assessment VO2Max measured';

ALTER TABLE fitness_assessment ADD CONSTRAINT fitness_assessment_pk PRIMARY KEY (
fitassess_date,
                                                                                member_no );

CREATE TABLE fitness_class (
    class_no                NUMBER(4) NOT NULL,
    centre_id               NUMBER(3) NOT NULL,
    class_datetime          DATE NOT NULL,
    class_descr             VARCHAR2(50 CHAR),
    class_max_participants  NUMBER(3) NOT NULL,
    class_sess_no           NUMBER(3) NOT NULL,
    class_cost              NUMBER(7, 2) NOT NULL,
    class_duration          NUMBER(3) NOT NULL,
    fac_room_no             NUMBER(3) NOT NULL,
    class_nature            CHAR(1 CHAR) NOT NULL,
    class_type_id           NUMBER(7) NOT NULL
);

ALTER TABLE fitness_class
    ADD CONSTRAINT chk_restrictions CHECK ( class_nature IN ( 'F', 'M', 'U' ) );

COMMENT ON COLUMN fitness_class.class_no IS
    'Unique within the centre class identifier ';

COMMENT ON COLUMN fitness_class.centre_id IS
    'Centre unique identifier';

COMMENT ON COLUMN fitness_class.class_datetime IS
    'Date time of the first class';

COMMENT ON COLUMN fitness_class.class_descr IS
    'Class description';

COMMENT ON COLUMN fitness_class.class_max_participants IS
    'Maximum number of class participants';

COMMENT ON COLUMN fitness_class.class_sess_no IS
    'No of sessions in that class';

COMMENT ON COLUMN fitness_class.class_cost IS
    'The cost of the class';

COMMENT ON COLUMN fitness_class.class_duration IS
    'Duration of a signle class in minutes';

COMMENT ON COLUMN fitness_class.fac_room_no IS
    'The unique within a centre facility id';

COMMENT ON COLUMN fitness_class.class_nature IS
    'Nature of the class: 
	- U: unrestricted
	- F: female
	- M: male';

COMMENT ON COLUMN fitness_class.class_type_id IS
    'Unique identifier of a class type';

ALTER TABLE fitness_class ADD CONSTRAINT class_pk PRIMARY KEY ( class_no,
                                                                centre_id );

CREATE TABLE member (
    member_no           NUMBER(8) NOT NULL,
    member_name         VARCHAR2(20 CHAR) NOT NULL,
    member_address      VARCHAR2(50 CHAR) NOT NULL,
    member_phone        CHAR(10 CHAR) NOT NULL,
    member_joindate     DATE NOT NULL,
    home_centre_id      NUMBER(3) NOT NULL,
    member_recommender  NUMBER(8)
);

COMMENT ON COLUMN member.member_no IS
    'Unique identifier of the member';

COMMENT ON COLUMN member.member_name IS
    'Member full name';

COMMENT ON COLUMN member.member_address IS
    'Member address';

COMMENT ON COLUMN member.member_phone IS
    'Member phone number';

COMMENT ON COLUMN member.member_joindate IS
    'Date when the member joined ';

COMMENT ON COLUMN member.home_centre_id IS
    'Centre unique identifier';

COMMENT ON COLUMN member.member_recommender IS
    'Unique identifier of the member';

ALTER TABLE member ADD CONSTRAINT member_pk PRIMARY KEY ( member_no );

CREATE TABLE member_session_attendance (
    mem_sess_date    DATE NOT NULL,
    mem_sess_attend  CHAR(1 CHAR) NOT NULL,
    sign_up_no       NUMBER(7) NOT NULL
);

ALTER TABLE member_session_attendance
    ADD CONSTRAINT chk_attendance CHECK ( mem_sess_attend IN ( 'N', 'Y' ) );

COMMENT ON COLUMN member_session_attendance.mem_sess_date IS
    'Date of the session';

COMMENT ON COLUMN member_session_attendance.mem_sess_attend IS
    'Defines whether the member attended a session:
	- Y: yes
	- N: no';

COMMENT ON COLUMN member_session_attendance.sign_up_no IS
    'Sign up unique identifier number';

ALTER TABLE member_session_attendance ADD CONSTRAINT member_session_attendance_pk
PRIMARY KEY ( mem_sess_date,
                                                                                  sign_up_no );

CREATE TABLE sign_up (
    member_no             NUMBER(8) NOT NULL,
    centre_id             NUMBER(3) NOT NULL,
    class_no              NUMBER(4) NOT NULL,
    sign_up_pay_date      DATE NOT NULL,
    sign_up_total_attend  NUMBER(3) NOT NULL,
    sign_up_no            NUMBER(7) NOT NULL
);

COMMENT ON COLUMN sign_up.member_no IS
    'Unique identifier of the member';

COMMENT ON COLUMN sign_up.centre_id IS
    'Centre unique identifier';

COMMENT ON COLUMN sign_up.class_no IS
    'Unique within the centre class identifier ';

COMMENT ON COLUMN sign_up.sign_up_pay_date IS
    'Date when member signed up for the class';

COMMENT ON COLUMN sign_up.sign_up_total_attend IS
    'Total attendance per one signed up contract';

COMMENT ON COLUMN sign_up.sign_up_no IS
    'Sign up unique identifier number';

ALTER TABLE sign_up ADD CONSTRAINT sign_up_pk PRIMARY KEY ( sign_up_no );

ALTER TABLE sign_up
    ADD CONSTRAINT sign_up_nk UNIQUE ( member_no,
                                       centre_id,
                                       class_no );

CREATE TABLE staff (
    staff_id                   NUMBER(8) NOT NULL,
    staff_fname                VARCHAR2(20 CHAR) NOT NULL,
    staff_lname                VARCHAR2(20 CHAR) NOT NULL,
    staff_phone                CHAR(10 CHAR) NOT NULL,
    staff_start_date           DATE NOT NULL,
    staff_role                 CHAR(1 CHAR) NOT NULL,
    staff_first_aid_certified  CHAR(1 CHAR) NOT NULL,
    centre_id                  NUMBER(3) NOT NULL
);

ALTER TABLE staff
    ADD CONSTRAINT chk_staff_role CHECK ( staff_role IN ( 'A', 'C', 'D', 'M', 'P',
                                                          'S', 'T' ) );

ALTER TABLE staff
    ADD CONSTRAINT chk_first_aid_certified CHECK ( staff_first_aid_certified IN (
    'N', 'Y' ) );

COMMENT ON COLUMN staff.staff_id IS
    'Unique identifier for the staff';

COMMENT ON COLUMN staff.staff_fname IS
    'First name of the staff member';

COMMENT ON COLUMN staff.staff_lname IS
    'Last name of the staff member';

COMMENT ON COLUMN staff.staff_phone IS
    'Staff member phone number';

COMMENT ON COLUMN staff.staff_start_date IS
    'Staff member first day of employment';

COMMENT ON COLUMN staff.staff_role IS
    'Role of the staff member:
	- A: administrator 
	- C: cleaner
	- D: instructor dry
	- M: manager 
	- P: instructor pool
	- S: sales
	- T: security';

COMMENT ON COLUMN staff.staff_first_aid_certified IS
    'Defines whether the staff member is first aid certified:
	- Y: yes
	- N: no';

COMMENT ON COLUMN staff.centre_id IS
    'Centre unique identifier';

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( staff_id );

ALTER TABLE facility
    ADD CONSTRAINT centre_facility FOREIGN KEY ( centre_id )
        REFERENCES centre ( centre_id );

ALTER TABLE member
    ADD CONSTRAINT centre_member FOREIGN KEY ( home_centre_id )
        REFERENCES centre ( centre_id );

ALTER TABLE staff
    ADD CONSTRAINT centre_staff FOREIGN KEY ( centre_id )
        REFERENCES centre ( centre_id );

ALTER TABLE fitness_class
    ADD CONSTRAINT class_facility FOREIGN KEY ( fac_room_no,
                                                centre_id )
        REFERENCES facility ( fac_room_no,
                              centre_id );

ALTER TABLE sign_up
    ADD CONSTRAINT class_sign_up FOREIGN KEY ( class_no,
                                               centre_id )
        REFERENCES fitness_class ( class_no,
                                   centre_id );

ALTER TABLE class_staff
    ADD CONSTRAINT class_staff FOREIGN KEY ( class_no,
                                             centre_id )
        REFERENCES fitness_class ( class_no,
                                   centre_id );

ALTER TABLE centre
    ADD CONSTRAINT manager_centre FOREIGN KEY ( manager_id )
        REFERENCES staff ( staff_id );

ALTER TABLE fitness_assessment
    ADD CONSTRAINT member_fitness_assessment FOREIGN KEY ( member_no )
        REFERENCES member ( member_no );

ALTER TABLE member
    ADD CONSTRAINT member_recommender FOREIGN KEY ( member_recommender )
        REFERENCES member ( member_no );

ALTER TABLE sign_up
    ADD CONSTRAINT member_sign_up FOREIGN KEY ( member_no )
        REFERENCES member ( member_no );

ALTER TABLE member_session_attendance
    ADD CONSTRAINT sign_up_attendance FOREIGN KEY ( sign_up_no )
        REFERENCES sign_up ( sign_up_no );

ALTER TABLE class_staff
    ADD CONSTRAINT staff_class FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE fitness_assessment
    ADD CONSTRAINT staff_fitness_assessment FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE fitness_class
    ADD CONSTRAINT type_class FOREIGN KEY ( class_type_id )
        REFERENCES class_type ( class_type_id );


SPOOL OFF
SET ECHO OFF

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             1
-- ALTER TABLE                             30
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0